schema_version: 1
customer:
  name: vpn-customer-stage1-15-cust-0006
  peer:
    public_ip: 100.54.120.200
    remote_id: 100.54.120.200
    psk_secret_ref: /muxingrpdb/dev/customers/vpn-customer-stage1-15-cust-0006/psk
  selectors:
    local_subnets:
    - 172.31.54.39/32
    - 172.31.34.79/32
    - 194.138.36.80/28
    - 10.128.4.6/32
    remote_subnets:
    - 10.129.3.132/32
    remote_host_cidrs:
    - 10.129.3.132/32
  transport:
    tunnel_mtu: 1436
  dynamic_peer_ip:
    enabled: true
    source: device_registry_ddns
    device_registry:
      serial_number: vpn-customer-stage1-15-cust-0006
      password_secret_ref: /muxingrpdb/dev/customers/vpn-customer-stage1-15-cust-0006/dynamic-peer-ip-password
    reapply:
      mode: remove_reapply
      update_remote_id_when_equal_to_peer_ip: false
  ipsec:
    auto: start
    remote_id: 100.54.120.200
    ike_version: ikev2
    ike_policies:
    - aes256-sha256-modp2048
    - aes256-sha256-modp4096
    esp_policies:
    - aes256-sha256-modp2048
    - aes256-sha256-modp4096
    dpddelay: 10s
    dpdtimeout: 120s
    dpdaction: restart
    replay_protection: true
    pfs_required: false
    pfs_groups:
    - modp2048
    - modp4096
    mobike: false
    fragmentation: true
    clear_df_bit: true
    path_mtu: 1400
  post_ipsec_nat:
    enabled: false
    mode: disabled
  outside_nat:
    enabled: true
    mode: netmap
    mapping_strategy: one_to_one
    real_subnets:
    - 194.138.36.86/32
    translated_subnets:
    - 10.128.4.6/32
    tcp_mss_clamp: 1360
    route_via: 172.31.63.44
    route_dev: ens36
