#!/usr/bin/env python3
"""strongSwan configuration rendering."""

from __future__ import annotations

import ipaddress
from pathlib import Path
from typing import Any, Dict, List, Tuple

from .core import BASE
from .customers import subnet_list


def render_strongswan(global_cfg: Dict[str, Any], modules: List[Dict[str, Any]]) -> Tuple[Path, Path, int]:
    ipsec_global = global_cfg.get("ipsec", {})
    render_dir = Path(str(ipsec_global.get("render_dir", BASE / "config" / "rendered")))
    render_dir.mkdir(parents=True, exist_ok=True)
    conf_path = render_dir / "ipsec.generated.conf"
    secrets_path = render_dir / "ipsec.generated.secrets"

    ike = str(ipsec_global.get("ike", "aes256-sha256-modp2048!"))
    esp = str(ipsec_global.get("esp", "aes256-sha256!"))
    forceencaps = str(ipsec_global.get("forceencaps", "no"))
    mobike = str(ipsec_global.get("mobike", "no"))
    fragmentation = str(ipsec_global.get("fragmentation", "yes"))
    ikelifetime = str(ipsec_global.get("ikelifetime", "28800s"))
    lifetime = str(ipsec_global.get("lifetime", "28800s"))
    dpddelay = str(ipsec_global.get("dpddelay", "30s"))
    dpdtimeout = str(ipsec_global.get("dpdtimeout", "120s"))
    dpdaction = str(ipsec_global.get("dpdaction", "restart"))
    default_auto = str(ipsec_global.get("auto", "route"))
    local_id_default = str(ipsec_global.get("local_id", global_cfg["public_ip"]))

    conf_lines: List[str] = [
        "# AUTOGENERATED by /etc/muxer/src/muxctl.py",
        "# Copy to /etc/ipsec.conf for muxer-terminated mode.",
        "",
        "config setup",
        "    uniqueids=no",
        "",
        "conn %default",
        "    keyexchange=ikev2",
        "    type=tunnel",
        "    authby=psk",
        "    rekey=yes",
        "    reauth=no",
        "    keyingtries=%forever",
        f"    dpddelay={dpddelay}",
        f"    dpdtimeout={dpdtimeout}",
        f"    dpdaction={dpdaction}",
        f"    forceencaps={forceencaps}",
        f"    mobike={mobike}",
        f"    fragmentation={fragmentation}",
        f"    ikelifetime={ikelifetime}",
        f"    lifetime={lifetime}",
        f"    ike={ike}",
        f"    esp={esp}",
        "",
    ]
    secret_lines: List[str] = [
        "# AUTOGENERATED by /etc/muxer/src/muxctl.py",
        "# Copy to /etc/ipsec.secrets",
        "",
    ]

    conn_count = 0
    for module in modules:
        ipsec_cfg = module.get("ipsec", {}) or {}
        local_subnets = subnet_list(ipsec_cfg.get("local_subnets", []))
        remote_subnets = subnet_list(ipsec_cfg.get("remote_subnets", []))
        if not local_subnets or not remote_subnets:
            continue

        name = str(module["name"])
        peer_ip = str(module["peer_ip"]).split("/")[0]
        ipaddress.ip_address(peer_ip)

        local_id = str(ipsec_cfg.get("local_id", local_id_default))
        remote_id = str(ipsec_cfg.get("remote_id", peer_ip))
        psk = str(ipsec_cfg.get("psk", "")).strip()
        if not psk:
            original = module.get("_rpdb_original") or {}
            peer_doc = original.get("peer") if isinstance(original, dict) else {}
            psk_secret_ref = str((peer_doc or {}).get("psk_secret_ref") or "").strip()
            if psk_secret_ref:
                raise SystemExit(
                    f"{name}: termination-mode rendering cannot use peer.psk_secret_ref "
                    f"({psk_secret_ref}) directly yet. Resolve the secret into ipsec.psk before "
                    "running render-ipsec or muxer termination mode."
                )
            raise SystemExit(f"{name}: ipsec.psk is required for termination-mode rendering")
        auto = str(ipsec_cfg.get("auto", default_auto))

        conf_lines.extend(
            [
                f"conn {name}",
                "    left=%defaultroute",
                f"    leftid={local_id}",
                f"    leftsubnet={','.join(local_subnets)}",
                f"    right={peer_ip}",
                f"    rightid={remote_id}",
                f"    rightsubnet={','.join(remote_subnets)}",
                f"    auto={auto}",
                "",
            ]
        )
        secret_lines.append(f'{local_id} {remote_id} : PSK "{psk}"')
        conn_count += 1

    conf_path.write_text("\n".join(conf_lines).rstrip() + "\n", newline="\n")
    secrets_path.write_text("\n".join(secret_lines).rstrip() + "\n", newline="\n")
    return conf_path, secrets_path, conn_count
