schema_version: 1

customer:
  name: example-cgnat-customer-1-local-pki
  customer_class: strict-non-nat
  peer:
    public_ip: 203.0.113.61
    psk_secret_ref: /muxingrpdb/customers/example-cgnat-customer-1-local-pki/psk
  selectors:
    local_subnets:
      - 23.20.31.151/32
      - 10.20.40.10/32
    remote_subnets:
      - 10.20.30.10/32
  backend:
    cluster: non-nat
  protocols:
    udp500: true
    udp4500: false
    esp50: true
  natd_rewrite:
    enabled: true
  post_ipsec_nat:
    enabled: true
    mode: netmap
    mapping_strategy: one_to_one
    real_subnets:
      - 10.20.30.10/32
    translated_subnets:
      - 10.20.20.10/32
    core_subnets:
      - 23.20.31.151/32
      - 194.138.36.86/32
  outside_nat:
    enabled: true
    mode: netmap
    mapping_strategy: one_to_one
    real_subnets:
      - 194.138.36.86/32
    translated_subnets:
      - 10.20.40.10/32
    route_via: 172.31.63.44
    route_dev: ens36
  transport:
    mode: cgnat
    tunnel_mtu: 1436
    cgnat:
      service_profile: scenario1
      outer_identity_ref: customer-router-1/example-cgnat-customer-1-local-pki
      outer_auth_ref: pki/cgnat/customer-router-1
      customer_loopback_ip: 10.250.1.10
      known_inside_identity: 10.20.30.10/32
      service_reachable_subnets:
        - 23.20.31.151/32
        - 194.138.36.86/32
      pki:
        mode: local_generate
        ca_common_name: example-cgnat-customer-1-local-pki-outer-ca
        headend:
          identity_ref: cgnat-head-end/example-cgnat-customer-1-local-pki
          auth_ref: pki/cgnat/headend/example-cgnat-customer-1-local-pki
        customer:
          identity_ref: customer-router-1/example-cgnat-customer-1-local-pki
          auth_ref: pki/cgnat/customer-router-1/example-cgnat-customer-1-local-pki
          package_name: example-cgnat-customer-1-local-pki-customer-router-1
        trust:
          ca_ref: pki/cgnat/ca/example-cgnat-customer-1-local-pki
